name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Install yarn
        run: sudo npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Fix audit
        run: npm_config_yes=true npx yarn-audit-fix

      - name: Build
        run: yarn build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: build

      - name: Deploy
        # if: github.event_name == 'push' # FIXME: Uncomment after debug
        uses: actions/deploy-pages@v4
